name: TDLib ARM Release (GitHub Hosted)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit, branch or tag to checkout'
        required: false
        default: ''

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Build on ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [armv7, aarch64]
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Release Info
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.commit }}" == "master" || -z "${{ github.event.inputs.commit }}" ]]; then
            echo "release_name=tdlib-latest-ubuntu-${{ matrix.arch }}" >> $GITHUB_ENV
            echo "release_version=latest" >> $GITHUB_ENV
          else
            echo "release_name=tdlib-${{ github.event.inputs.commit }}-ubuntu-${{ matrix.arch }}" >> $GITHUB_ENV
            echo "release_version=${{ github.event.inputs.commit }}" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build TDLib
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64
          build-args: |
            ARCH=${{ matrix.arch }}
            TD_VERSION=${{ env.release_version }}
          outputs: type=local,dest=./artifacts

      - name: Package Artifacts
        run: |
          cd artifacts
          tar -czvf ${{ env.release_name }}-for-java.tar.gz tdlib/*
          mv *.tar.gz ../

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.release_name }}-for-java.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
